### PR TITLE
Fix permissions on crew applications

### LINKED ISSUE #565: [BUG] Crew Applications are visible by accessing the applications page directly
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

493e2aa

### Current Behavior

Crew recruitment applications can be accessed by visiting the application page directly and passing the role id, even if a user does not have permission to view that role's applications.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### How are you accessing AdamRMS?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cherry-john**
By submitting a PR for this repository you accept the contributor license agreement. 

### Description

Fix a permissions issue with crew role applications

### References
Closes #565 

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in the documentation repo
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

### CODE REVIEW

File: html/admin/project/crew/applications.php [hunk 1]
```diff
@@ -11,10 +11,10 @@
...
 if (!$PAGEDATA['role']) die($TWIG->render('404.twig', $PAGEDATA));
 
-if ($role['projectsVacantRoles_privateToPM'] == 1) {
-    if ($PAGEDATA['project']['projects_manager'] != $AUTH->data["users_userid"]) die($TWIG->render('404.twig', $PAGEDATA));
-} elseif ($role['projectsVacantRoles_applicationVisibleToUsers'] != null) {
-    if (!in_array($AUTH->data["users_userid"], explode(",",$role['projectsVacantRoles_applicationVisibleToUsers'])) and $PAGEDATA['project']['projects_manager'] != $AUTH->data["users_userid"]) die($TWIG->render('404.twig', $PAGEDATA));
+if ($PAGEDATA['role']['projectsVacantRoles_privateToPM'] == 1) {
+    if ($PAGEDATA['role']['projects_manager'] != $AUTH->data["users_userid"]) die($TWIG->render('404.twig', $PAGEDATA));
+} elseif ($PAGEDATA['role']['projectsVacantRoles_applicationVisibleToUsers'] != null) {
+    if (!in_array($AUTH->data["users_userid"], explode(",",$PAGEDATA['role']['projectsVacantRoles_applicationVisibleToUsers'])) and $PAGEDATA['project']['projects_manager'] != $AUTH->data["users_userid"]) die($TWIG->render('404.twig', $PAGEDATA));
```
Comment (Jbithell) [inline html/admin/project/crew/applications.php:17]: Does `$PAGEDATA['project']` exist either?

Comment (cherry-john) [reply html/admin/project/crew/applications.php]: Would help if I stage all the changes...

**Review by Jbithell — APPROVED** [review]
